### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by talex5** [kit-ty-kate/opam-build#3]
The README says:

> opam-build and opam-test are two opam plugins that
> To install it, simply call:

I found a description in the 0.1.0 release notes, so probably worth copying that to the README.

**Comment by kit-ty-kate** [comment]
Fixed by https://github.com/kit-ty-kate/opam-build/commit/f39e5d52b4c83c30c5c9aa6b12d6daa8f4dedf1b. Thanks!
